config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners, controllers: { registrations: 'registrations' }
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'home#index'

  resources :guesthouses, only: [:show, :new, :create, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
    get 'search_by_city', on: :collection
    get 'search_by_term', on: :collection

    resources :rooms, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member

    resources :seasonal_rates, only: [:new, :create]
    resources :bookings, only: [:new, :create]
    get 'validate-booking', to: 'bookings#validate'
  end

  resources :seasonal_rates, only: [:edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
  end

  resources :bookings, only: [:show] do
    post 'ongoing', on: :member
    post 'finished', on: :member
    post 'canceled', on: :member
    get 'confirmed-check-out', on: :member

    resources :reviews, only: [:new, :create]
  end
  
  resources :reviews, only: [] do
    get 'new-reply', on: :member
    post 'save-reply', on: :member
  end
  
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'my-bookings', to: 'bookings#my_bookings'
  get 'my-ongoing-bookings', to: 'bookings#my_ongoing_bookings'
  get 'my-reviews', to: 'reviews#my_reviews'

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end

      resources :rooms, only: [] do
        get 'validate-booking', to: 'bookings#validate'
      end
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest, optional: true
  belongs_to :room
  has_one :review

  enum status: { pending: 0, ongoing: 2, finished: 4, canceled: 6 }

  before_validation :generate_code, on: :create

  validates :start_date, :finish_date, :guests_number, :code, presence: true
  validates_with DatesAreFutureValidator, FinishDateIsLaterThanStartDateValidator, DatesAreAvailableValidator, on: :create
  validate :guests_number_respects_room_capacity

  private

  def guests_number_respects_room_capacity
    self.errors.add(:guests_number, 'deve respeitar a capacidade máxima do quarto') if self.guests_number.present? && self.guests_number > self.room.max_capacity
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::V1::ApiController
  def validate
    room = Room.find(params[:room_id])

    return render status: 404, json: { message: 'Pousada está inativa.' } if room.guesthouse.inactive?
    return render status: 404, json: { message: 'Quarto está inativo.' } if room.inactive?

    booking = room.bookings.build(booking_params)

    if booking.valid?
      booking.total_price = room.calculate_total_price(booking.start_date, booking.finish_date)
  
      render status: 200, json: booking.as_json(only: :total_price)
    else
      status = 
        if booking.errors.include? :base
          409
        else
          400
        end

      render status: status, json: { message: 'Parâmetros inválidos.', errors: booking.errors.full_messages }
    end
  end

  private

  def booking_params
    params.permit(:start_date, :finish_date, :guests_number)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  devise_group :app_user, contains: [:guest, :owner]

  before_action :authenticate_guest!, only: [:create]
  before_action :authenticate_owner!, only: [:ongoing, :confirmed_check_out, :finished, :my_ongoing_bookings]
  before_action :authenticate_app_user!, only: [:show, :my_bookings, :canceled]

  before_action :set_room, only: [:new, :create, :validate]
  before_action :set_booking, only: [:show, :ongoing, :confirmed_check_out, :finished, :canceled]

  before_action :check_owner, only: [:ongoing, :confirmed_check_out, :finished]
  before_action :check_app_user, only: [:show, :canceled]
  before_action :check_status_pending, only: [:ongoing, :canceled]
  before_action :check_status_ongoing, only: [:confirmed_check_out, :finished]
  before_action :check_start_date, only: [:ongoing, :canceled]
  
  def new
    @booking = @room.bookings.build
  end

  def validate
    @booking = @room.bookings.build(booking_params)

    if @booking.valid?
      @booking.total_price = @room.calculate_total_price(@booking.start_date, @booking.finish_date)
      session[:booking] = @booking
    else
      flash.now[:alert] = 'Não foi possível fazer a pré-reserva.'
      render :new
    end
  end

  def create
    @booking =
      if session[:booking].present?
        current_guest.bookings.build(session[:booking])
      else
        current.guest.bookings.build(booking_params)
      end

    if @booking.save
      session.delete(:booking)
      redirect_to my_bookings_path, notice: 'Reserva confirmada com sucesso.'
    else
      flash.now[:alert] = 'Não foi possível confirmar a reserva.'
      render :new
    end
  end

  def my_bookings
    if owner_signed_in?
      @bookings = []

      current_owner.guesthouse.rooms.each do |room|
        room.bookings.each do |booking|
          @bookings << booking
        end
      end
    elsif guest_signed_in?
      @bookings = current_guest.bookings
    end
    
    render :index
  end

  def my_ongoing_bookings
    @bookings = []

    current_owner.guesthouse.rooms.each do |room|
      room.bookings.ongoing.each do |booking|
        @bookings << booking
      end
    end

    render :index
  end

  def ongoing
    @booking.update!(status: :ongoing, check_in: Time.zone.now)

    redirect_to booking_path(@booking), notice: 'Check-In realizado com sucesso.'
  end

  def canceled
    @booking.canceled!

    redirect_to booking_path(@booking), notice: 'Reserva cancelada com sucesso.'
  end

  def confirmed_check_out
    @updated_total_price = @booking.room.calculate_proportional_total_price(@booking.check_in, Time.zone.now)
    session[:updated_total_price] = @updated_total_price
    
    render :confirm_check_out
  end

  def finished
    check_out_params = params.require(:booking).permit(:payment_method, :total_price)
    payment_method = check_out_params[:payment_method]
    total_price =
      if session[:updated_total_price].present?
        session[:updated_total_price]
      else
        check_out_params[:total_price]
      end

    @booking.update!(status: :finished, check_out: Time.zone.now, payment_method: payment_method, total_price: total_price)

    session.delete(:updated_total_price)

    redirect_to booking_path(@booking), notice: 'Check-Out realizado com sucesso.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :finish_date, :guests_number, :total_price, :room_id)
  end

  def set_room
    @room = Room.find(params[:room_id])
  end
  
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def check_owner
    redirect_to root_path, alert: 'Você não tem acesso a esse recurso.' unless current_owner == @booking.room.guesthouse.owner
  end

  def check_app_user
    redirect_to root_path, alert: 'Você não tem acesso a esse recurso.' unless current_guest == @booking.guest || current_owner == @booking.room.guesthouse.owner
  end

  def check_status_pending
    redirect_to root_path, alert: 'Recurso indisponível para esta reserva.' unless @booking.pending?
  end

  def check_status_ongoing
    redirect_to root_path, alert: 'Recurso indisponível para esta reserva.' unless @booking.ongoing?
  end
  
  def check_start_date
    return if guest_signed_in? && @booking.start_date - Time.zone.now.to_date >= 7
    return if owner_signed_in? && Time.zone.now.to_date >= @booking.start_date

    redirect_to root_path, alert: 'Recurso indisponível para esta reserva.'
  end
end

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <h3>Erros:</h3>
  <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/bookings/_form.html.erb
<h3>Informações da Reserva</h3>

<%= render 'errors' %>

<%= form_with model: [@room, @booking], url: room_validate_booking_path(@room), method: :get do |f| %>
  <div>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>
  <div>
    <%= f.label :finish_date %>
    <%= f.date_field :finish_date %>
  </div>
  <div>
    <%= f.label :guests_number %>
    <%= f.number_field :guests_number, min: 1, step: 1 %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/bookings/_room_details.html.erb
<h3>Detalhes do Quarto</h3>

<dl>
  <dt><%= Room.human_attribute_name :name %>:</dt>
  <dd><%= @room.name %></dd>
  <dt><%= Room.human_attribute_name :description %>:</dt>
  <dd><%= @room.description %></dd>
  <dt><%= Room.human_attribute_name :area %>:</dt>
  <dd><%= @room.area %>m²</dd>
  <dt><%= Room.human_attribute_name :max_capacity %>:</dt>
  <dd><%= @room.max_capacity %> pessoa(s)</dd>
  <dt><%= Room.human_attribute_name :daily_rate %>:</dt>
  <dd><%= number_to_currency(@room.daily_rate) %></dd>
  <dt><%= Room.human_attribute_name :has_bathroom %></dt>
  <dd><%= t("yesno.#{@room.has_bathroom?}") %></dd>
  <dt><%= Room.human_attribute_name :has_balcony %></dt>
  <dd><%= t("yesno.#{@room.has_balcony?}") %></dd>
  <dt><%= Room.human_attribute_name :has_air_conditioner %></dt>
  <dd><%= t("yesno.#{@room.has_air_conditioner?}") %></dd>
  <dt><%= Room.human_attribute_name :has_tv %></dt>
  <dd><%= t("yesno.#{@room.has_tv?}") %></dd>
  <dt><%= Room.human_attribute_name :has_wardrobe %></dt>
  <dd><%= t("yesno.#{@room.has_wardrobe?}") %></dd>
  <dt><%= Room.human_attribute_name :has_safe %></dt>
  <dd><%= t("yesno.#{@room.has_safe?}") %></dd>
  <dt><%= Room.human_attribute_name :is_accessible %></dt>
  <dd><%= t("yesno.#{@room.is_accessible?}") %></dd>
</dl>

app/views/bookings/confirm_check_out.html.erb
<h1>Resumo Check-Out</h1>

<dl>
  <dt><%= Booking.human_attribute_name :total_price %>:</dt>
  <dd><%= number_to_currency(@updated_total_price) %></dd>
</dl>

<%= form_with model: @booking, url: finished_booking_path(@booking), method: :post do |f| %>
  <div>
    <%= f.label :payment_method %>
    <%= f.text_field :payment_method %>
  </div>
  <div>
    <%= f.submit 'Confirmar Check-Out' %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1>Minhas Reservas</h1>

<% if @bookings.any? %>
  <table>
    <thead>
      <tr>
        <th><%= Booking.human_attribute_name :code %></th>
        <% if guest_signed_in? %>
          <th><%= Guesthouse.model_name.human %></th>
        <% end %>
        <th><%= Room.model_name.human %></th>
        <th><%= Booking.human_attribute_name :start_date %></th>
        <th><%= Booking.human_attribute_name :finish_date %></th>
        <th><%= Booking.human_attribute_name :guests_number %></th>
        <th><%= Booking.human_attribute_name :status %></th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= link_to booking.code, booking_path(booking) %></td>
          <% if guest_signed_in? %>
            <td><%= booking.room.guesthouse.trading_name %></td>
          <% end %>
          <td><%= booking.room.name %></td>
          <td><%= I18n.localize(booking.start_date) %></td>
          <td><%= I18n.localize(booking.finish_date) %></td>
          <td><%= booking.guests_number %></td>
          <td><%= t(booking.status) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Você ainda não tem nenhuma reserva.</p>
<% end %>

app/views/bookings/new.html.erb
<h1>Realizar Reserva</h1>

<%= render 'room_details' %>

<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>Detalhes da Reserva</h1>

<dl>
  <dt><%= Booking.human_attribute_name :code %>:</dt>
  <dd><%= @booking.code %></dd>
  <% if owner_signed_in? %>
    <dt><%= Guest.model_name.human %>:</dt>
    <dd><%= guest_full_name(@booking.guest) %></dd>
  <% elsif guest_signed_in? %>
    <dt><%= Guesthouse.model_name.human %>:</dt>
    <dd><%= link_to @booking.room.guesthouse.trading_name, guesthouse_path(@booking.room.guesthouse) %></dd>
  <% end %>
  <dt><%= Room.model_name.human %>:</dt>
  <dd><%= link_to @booking.room.name, room_path(@booking.room) %></dd>
  <dt><%= Booking.human_attribute_name :start_date %>:</dt>
  <dd><%= I18n.localize(@booking.start_date) %></dd>
  <dt><%= Booking.human_attribute_name :finish_date %>:</dt>
  <dd><%= I18n.localize(@booking.finish_date) %></dd>
  <dt><%= Booking.human_attribute_name :guests_number %>:</dt>
  <dd><%= @booking.guests_number %></dd>
  <dt><%= Booking.human_attribute_name :total_price %>:</dt>
  <dd><%= number_to_currency(@booking.total_price) %></dd>
  <dt><%= Booking.human_attribute_name :status %>:</dt>
  <dd><%= t(@booking.status) %></dd>
  <% if @booking.finished? %>
    <dt><%= Booking.human_attribute_name :payment_method %>:</dt>
    <dd><%= @booking.payment_method %></dd>
  <% end %>
</dl>

<% if @booking.review.present? %>
  <section id="review">
    <h2>Sua Avaliação</h2>

    <h3><%= Review.human_attribute_name :rating %>: <%= @booking.review.rating %></h3>
    <h3><%= Review.human_attribute_name :comment %></h3>
    <p><%= @booking.review.comment %></p>
  </section>
<% end %>

<% if @booking.pending? && (guest_signed_in? && @booking.start_date - Time.zone.now.to_date >= 7 || owner_signed_in? && Time.zone.now.to_date - @booking.start_date >= 2) %>
  <%= button_to 'Cancelar Reserva', canceled_booking_path(@booking), class: 'button' %>
<% end %>

<% if owner_signed_in? %>
  <% if @booking.pending? && Time.zone.now.to_date >= @booking.start_date %>
    <%= button_to 'Realizar Check-In', ongoing_booking_path(@booking), class: 'button' %>
  <% end %>

  <% if @booking.ongoing? %>
    <%= link_to 'Realizar Check-Out', confirmed_check_out_booking_path(@booking), class: 'button' %>
  <% end %>
<% end %>

<% if @booking.finished? && @booking.review.nil? && guest_signed_in? %>
  <%= link_to 'Avaliar Estadia', new_booking_review_path(@booking), class: 'button' %>
<% end %>

app/views/bookings/validate.html.erb
<h3>Resumo da Reserva</h3>

<dl>
  <dt><%= Booking.human_attribute_name :total_price %>:</dt>
  <dd><%= number_to_currency(@booking.total_price) %></dd>

  <% if guest_signed_in? %>
  <dt><%= Booking.human_attribute_name :start_date %>:</dt>
  <dd><%= I18n.localize(@booking.start_date) %></dd>
  <dt><%= Guesthouse.human_attribute_name :check_in %>:</dt>
  <dd><%= guesthouse_format_time(@booking.room.guesthouse.check_in) %></dd>
  <dt><%= Booking.human_attribute_name :finish_date %>:</dt>
  <dd><%= I18n.localize(@booking.finish_date) %></dd>
  <dt><%= Guesthouse.human_attribute_name :check_out %>:</dt>
  <dd><%= guesthouse_format_time(@booking.room.guesthouse.check_out) %></dd>
  <dt><%= Room.model_name.human %>:</dt>
  <dd><%= @booking.room.name %></dd>
  <dt><%= Guesthouse.human_attribute_name :payment_methods %>:</dt>
  <dd><%= @booking.room.guesthouse.payment_methods %></dd>
  <% end %>
</dl>

<%= button_to 'Confirmar Reserva', room_bookings_path, class: 'input-button' %>