config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners, controllers: { registrations: 'registrations' }
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'home#index'

  resources :guesthouses, only: [:show, :new, :create, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
    get 'search_by_city', on: :collection
    get 'search_by_term', on: :collection

    resources :rooms, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member

    resources :seasonal_rates, only: [:new, :create]
    resources :bookings, only: [:new, :create]
    get 'validate-booking', to: 'bookings#validate'
  end

  resources :seasonal_rates, only: [:edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
  end

  resources :bookings, only: [:show] do
    post 'ongoing', on: :member
    post 'finished', on: :member
    post 'canceled', on: :member
    get 'confirmed-check-out', on: :member

    resources :reviews, only: [:new, :create]
  end
  
  resources :reviews, only: [] do
    get 'new-reply', on: :member
    post 'save-reply', on: :member
  end
  
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'my-bookings', to: 'bookings#my_bookings'
  get 'my-ongoing-bookings', to: 'bookings#my_ongoing_bookings'
  get 'my-reviews', to: 'reviews#my_reviews'

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end

      resources :rooms, only: [] do
        get 'validate-booking', to: 'bookings#validate'
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :guesthouse
  has_many :seasonal_rates
  has_many :bookings
  has_many :guests, through: :bookings

  enum status: { active: 0, inactive: 2 }

  validates :name, :description, :area, :max_capacity, :daily_rate, presence: true

  def calculate_total_price(start_date, finish_date)
    stay_range = Range.new(start_date.to_date, finish_date.to_date)
    seasonal_rates = SeasonalRate.active.where(room_id: self.id)

    return stay_range.count * self.daily_rate unless seasonal_rates.present?

    seasonal_total_price = 0
    regular_days = stay_range.to_a

    stay_range.each do |day|
      seasonal_rates.each do |seasonal_rate|
        seasonal_rate_range = Range.new(seasonal_rate.start_date.to_date, seasonal_rate.finish_date.to_date)

        if seasonal_rate_range.include? day
          seasonal_total_price += seasonal_rate.rate
          regular_days.delete(day)
        end
      end
    end

    return seasonal_total_price unless regular_days.present?

    seasonal_total_price + (regular_days.count * self.daily_rate)
  end

  def calculate_proportional_total_price(check_in, check_out)
    check_out += 1.day if check_out.strftime('%H:%M:%S') > self.guesthouse.check_out.strftime('%H:%M:%S')

    calculate_total_price(check_in, check_out)
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::ApiController
  def index
    guesthouse = Guesthouse.find(params[:guesthouse_id])

    return render status: 404, json: { message: 'Pousada está inativa.' } if guesthouse.inactive?

    rooms = guesthouse.rooms.active

    render status: 200, json: rooms.as_json(only: [:id, :name, :description, :area, :daily_rate, :guesthouse_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :activated, :deactivated]

  before_action :set_room, only: [:show, :edit, :update, :activated, :deactivated]
  before_action :set_guesthouse, only: [:new, :create]
  
  before_action :check_owner, only: [:new, :create, :edit, :update, :activated, :deactivated]
  before_action :check_room_status, only: [:show]

  def show; end

  def new
    @room = @guesthouse.rooms.build
  end

  def create
    @room = @guesthouse.rooms.build(room_params)

    if @room.save
      redirect_to room_path(@room), notice: 'Quarto cadastrado com sucesso.'
    else
      flash.now[:alert] = 'Não foi possível cadastrar o quarto.'
      render :new
    end
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room), notice: 'Quarto atualizado com sucesso.'
    else
      flash.now[:alert] = 'Não foi possível atualizar o quarto.'
      render :edit
    end
  end

  def activated
    @room.active!

    redirect_to room_path(@room), notice: 'O quarto foi ativado com sucesso.'
  end

  def deactivated
    @room.inactive!

    redirect_to room_path(@room), notice: 'O quarto foi desativado com sucesso.'
  end

  private

  def room_params
    params.require(:room).permit(:name, :description, :area, :max_capacity, :daily_rate, :has_bathroom, :has_balcony, :has_air_conditioner, :has_tv, :has_wardrobe, :has_safe, :is_accessible)
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def set_guesthouse
    @guesthouse = Guesthouse.find(params[:guesthouse_id])
  end

  def check_owner
    if @guesthouse.present?
      return if current_owner == @guesthouse.owner
    else
      return if current_owner == @room.guesthouse.owner
    end

    redirect_to root_path, alert: 'Você não tem acesso a esse recurso.'
  end

  def check_room_status
    unless current_owner == @room.guesthouse.owner
      redirect_to root_path, alert: 'Este quarto está indisponível.' if @room.inactive?
    end
  end
end

app/views/rooms/_errors.html.erb
<% if @room.errors.any? %>
  <h3>Erros:</h3>
  <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/rooms/_form.html.erb
<%= render 'errors' %>

<%= form_with model: [@guesthouse, @room] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.number_field :area, min: 1, step: 1 %>
  </div>
  <div>
    <%= f.label :max_capacity %>
    <%= f.number_field :max_capacity, min: 1, step: 1 %>
  </div>
  <div>
    <%= f.label :daily_rate %>
    <%= f.number_field :daily_rate, min: 0.01, step: 0.01 %>
  </div>
  <div>
    <%= f.label :has_bathroom %>
    <%= f.check_box :has_bathroom %>
  </div>
  <div>
    <%= f.label :has_balcony %>
    <%= f.check_box :has_balcony %>
  </div>
  <div>
    <%= f.label :has_air_conditioner %>
    <%= f.check_box :has_air_conditioner %>
  </div>
  <div>
    <%= f.label :has_tv %>
    <%= f.check_box :has_tv %>
  </div>
  <div>
    <%= f.label :has_wardrobe %>
    <%= f.check_box :has_wardrobe %>
  </div>
  <div>
    <%= f.label :has_safe %>
    <%= f.check_box :has_safe %>
  </div>
  <div>
    <%= f.label :is_accessible %>
    <%= f.check_box :is_accessible %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<dl>
  <dt><%= Room.human_attribute_name :name %>:</dt>
  <dd><%= link_to room.name, room_path(room) %></dd>
  <dt><%= Room.human_attribute_name :description %>:</dt>
  <dd><%= room.description %></dd>
  <dt><%= Room.human_attribute_name :area %>:</dt>
  <dd><%= room.area %>m²</dd>
  <dt><%= Room.human_attribute_name :daily_rate %>:</dt>
  <dd><%= number_to_currency(room.daily_rate) %></dd>
</dl>

app/views/rooms/edit.html.erb
<h1>Editar Quarto</h1>

<%= render 'form' %>

app/views/rooms/new.html.erb
<h1>Cadastrar novo Quarto</h1>

<%= render 'form' %>

app/views/rooms/show.html.erb
<h1><%= @room.guesthouse.trading_name %> - <%= @room.name %></h1>

<% if owner_signed_in? && @room.guesthouse.owner == current_owner %>
  <div class="owner-actions">
    <%= link_to 'Editar', edit_room_path(@room), class: 'button' %>
    <%= link_to 'Adicionar Preço Sazonal', new_room_seasonal_rate_path(@room), class: 'button' %>
    <% if @room.active? %>
      <%= button_to 'Desativar Quarto', deactivated_room_path(@room), class: 'button' %>
    <% else %>
      <%= button_to 'Ativar Quarto', activated_room_path(@room), class: 'button' %>
    <% end %>
  </div>
<% end %>

<dl>
  <dt><%= Room.human_attribute_name :name %>:</dt>
  <dd><%= @room.name %></dd>
  <dt><%= Room.human_attribute_name :description %>:</dt>
  <dd><%= @room.description %></dd>
  <dt><%= Room.human_attribute_name :area %>:</dt>
  <dd><%= @room.area %>m²</dd>
  <dt><%= Room.human_attribute_name :max_capacity %>:</dt>
  <dd><%= @room.max_capacity %> pessoa(s)</dd>
  <dt><%= Room.human_attribute_name :daily_rate %>:</dt>
  <dd><%= number_to_currency(@room.daily_rate) %></dd>
  <dt><%= Room.human_attribute_name :has_bathroom %></dt>
  <dd><%= t("yesno.#{@room.has_bathroom?}") %></dd>
  <dt><%= Room.human_attribute_name :has_balcony %></dt>
  <dd><%= t("yesno.#{@room.has_balcony?}") %></dd>
  <dt><%= Room.human_attribute_name :has_air_conditioner %></dt>
  <dd><%= t("yesno.#{@room.has_air_conditioner?}") %></dd>
  <dt><%= Room.human_attribute_name :has_tv %></dt>
  <dd><%= t("yesno.#{@room.has_tv?}") %></dd>
  <dt><%= Room.human_attribute_name :has_wardrobe %></dt>
  <dd><%= t("yesno.#{@room.has_wardrobe?}") %></dd>
  <dt><%= Room.human_attribute_name :has_safe %></dt>
  <dd><%= t("yesno.#{@room.has_safe?}") %></dd>
  <dt><%= Room.human_attribute_name :is_accessible %></dt>
  <dd><%= t("yesno.#{@room.is_accessible?}") %></dd>
</dl>

<% unless owner_signed_in? %>
  <%= link_to 'Reserva Prévia', new_room_booking_path(@room) %>
<% end %>

<section id="room-seasonal-rates">
  <% if owner_signed_in? && current_owner == @room.guesthouse.owner %>
    <h3>Preços Sazonais</h3>
    <% if @room.seasonal_rates.any? %>
      <table>
        <thead>
          <tr>
            <th><%= SeasonalRate.human_attribute_name :start_date %></th>
            <th><%= SeasonalRate.human_attribute_name :finish_date %></th>
            <th><%= SeasonalRate.human_attribute_name :rate %></th>
            <th colspan="2" >Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @room.seasonal_rates.each do |seasonal_rate| %>
            <tr>
              <td><%= localize(seasonal_rate.start_date) %></td>
              <td><%= localize(seasonal_rate.finish_date) %></td>
              <td><%= number_to_currency(seasonal_rate.rate) %></td>
              <td><%= link_to 'Editar', edit_seasonal_rate_path(seasonal_rate) %></td>
              <% if seasonal_rate.active? %>
                <td><%= button_to 'Desativar', deactivated_seasonal_rate_path(seasonal_rate) %></td>
              <% else %>
                <td><%= button_to 'Ativar', activated_seasonal_rate_path(seasonal_rate) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Não há preços sazonais cadastrados.</p>
    <% end %>
  <% end %>
</section>