config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners, controllers: { registrations: 'registrations' }
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'home#index'

  resources :guesthouses, only: [:show, :new, :create, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
    get 'search_by_city', on: :collection
    get 'search_by_term', on: :collection

    resources :rooms, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member

    resources :seasonal_rates, only: [:new, :create]
    resources :bookings, only: [:new, :create]
    get 'validate-booking', to: 'bookings#validate'
  end

  resources :seasonal_rates, only: [:edit, :update] do
    post 'activated', on: :member
    post 'deactivated', on: :member
  end

  resources :bookings, only: [:show] do
    post 'ongoing', on: :member
    post 'finished', on: :member
    post 'canceled', on: :member
    get 'confirmed-check-out', on: :member

    resources :reviews, only: [:new, :create]
  end
  
  resources :reviews, only: [] do
    get 'new-reply', on: :member
    post 'save-reply', on: :member
  end
  
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'my-bookings', to: 'bookings#my_bookings'
  get 'my-ongoing-bookings', to: 'bookings#my_ongoing_bookings'
  get 'my-reviews', to: 'reviews#my_reviews'

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end

      resources :rooms, only: [] do
        get 'validate-booking', to: 'bookings#validate'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PousadariaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <p>Pousadaria</p>
      <% end %>

      <%= form_with url: search_by_term_guesthouses_path, method: :get do |f| %>
        <%= f.label :query, 'Buscar Pousadas' %>
        <%= f.text_field :query %>
        <%= f.submit 'Buscar' %>
      <% end %>

      <nav>
        <ul id="header-links">
          <% if owner_signed_in? %>
            <li><%= owner_description(current_owner) %></li>
            <% if current_owner.guesthouse %>
              <li><%= link_to 'Minha Pousada', my_guesthouse_path %></li>
              <li><%= link_to 'Reservas', my_bookings_path %></li>
              <li><%= link_to 'Reservas Em Andamento', my_ongoing_bookings_path %></li>
              <li><%= link_to 'Avaliações', my_reviews_path %></li>
            <% else %>
              <li><%= link_to 'Cadastrar Pousada', new_guesthouse_path %></li>
            <% end %>
            <li><%= button_to 'Sair', destroy_owner_session_path, method: :delete, class: 'button' %></li>
          <% elsif guest_signed_in? %>
            <li><%= guest_full_name(current_guest) %></li>
            <li><%= link_to 'Minhas Reservas', my_bookings_path %></li>
            <li><%= link_to 'Minhas Avaliações', my_reviews_path %></li>
            <li><%= button_to 'Sair', destroy_guest_session_path, method: :delete, class: 'button' %></li>
          <% else %>
            <li id="guest-session-links">Hóspede: <%= link_to 'Registrar', new_guest_registration_path, class: 'session-button' %> | <%= link_to 'Entrar', new_guest_session_path, class: 'session-button' %></li>
            <li id="owner-session-links">Proprietário: <%= link_to 'Registrar', new_owner_registration_path, class: 'session-button' %> | <%= link_to 'Entrar', new_owner_session_path, class: 'session-button' %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <div id="flash-messages">
      <p id="alert-message"><%= alert %></p>
      <p id="notice-message"><%= notice %></p>
    </div>

    <main>
      <%= yield %>
    </main>
  </body>
</html>